version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
triggers:
  push:
    branches:
      exclude:
        - master
      include:
        - dev
stages:
  - stage:
    name: compile
    displayName: 编译
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 23.11.1
        commands:
          - node --version
          - npm --version
          - npm install
          - rm -rf ./dist
          - npm run build:test
        strategy: {}
      - step: build@nodejs
        name: deploy_to_cos
        displayName: 部署到腾讯云 COS 测试环境
        nodeVersion: 23.11.1
        commands:
          - npm run deploy:test
        dependsOn: build_nodejs
        strategy: {}
