version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 23.11.1
        commands:
          - node --version
          - npm --version
          - npm install
          - rm -rf ./dist
          - npm run build:prod
        strategy: {}
      - step: build@nodejs
        name: deploy_to_cos
        displayName: 部署到腾讯云 COS
        nodeVersion: 23.11.1
        commands:
          - npm run deploy:prod
        dependsOn: build_nodejs
        strategy: {}
